#DEV environment with YAML

app:
 message: This is the property file for the ${spring.application.name} specific for dev environment

spring:
 datasource:
  drive-class-name: org.h2.Driver
  url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  username: sa
  password: sa